# Generated by Django 3.2.5 on 2021-08-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroesapp', '0002_rename_superhero_superheroes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Superheroes',
            new_name='Superheroe',
        ),
    ]
