# Generated by Django 3.2.5 on 2021-08-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroesapp', '0003_rename_superheroes_superheroe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Superheroe',
            new_name='Superhero',
        ),
    ]
